name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/00-RELEASENOTES'
      - '**/COPYING'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/00-RELEASENOTES'
      - '**/COPYING'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: make
        run: make -j4 all-with-unit-tests SERVER_CFLAGS='-Werror' BUILD_TLS=yes USE_FAST_FLOAT=yes
      - name: validate commands.def up to date
        run: |
          touch src/commands/ping.json
          make commands.def
          dirty="$(git diff)"
          if [[ ! -z "$dirty" ]]; then echo "$dirty"; exit 1; fi
