name: E2E Triage

# Fork e2e only: a macOS test job, to exercise the macOS verifier.
on:
  push:
    branches-ignore: [unstable]
  pull_request:

permissions:
  contents: read

jobs:
  test-macos-incr:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: make
        run: make -j3 SERVER_CFLAGS='-Werror'
      - name: test
        run: ./runtest --single unit/type/incr --verbose --dump-logs
