name: Targeted commandresult loop

on:
  workflow_dispatch:
    inputs:
      use_repo:
        description: "repo owner and name"
        default: "valkey-io/valkey"
      use_git_ref:
        description: "git branch or sha to use"
        default: "unstable"
      loops:
        description: "number of commandresult repetitions"
        default: "100"
  workflow_call:
    inputs:
      use_repo:
        description: "repo owner and name"
        required: false
        type: string
        default: "valkey-io/valkey"
      use_git_ref:
        description: "git branch or sha to use"
        required: false
        type: string
        default: "unstable"
      loops:
        description: "number of commandresult repetitions"
        required: false
        type: string
        default: "100"

permissions:
  contents: read

jobs:
  alpine-commandresult-loop:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    container: alpine:latest
    steps:
      - name: prep
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        run: |
          echo "GITHUB_REPOSITORY=${{ inputs.use_repo || github.event.inputs.use_repo }}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{ inputs.use_git_ref || github.event.inputs.use_git_ref }}" >> $GITHUB_ENV
          echo "loops=${{ inputs.loops || github.event.inputs.loops }}" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.use_repo || github.event.inputs.use_repo || github.repository }}
          ref: ${{ inputs.use_git_ref || github.event.inputs.use_git_ref || github.ref }}
      - name: Install libbacktrace
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ianlancetaylor/libbacktrace
          ref: b9e40069c0b47a722286b94eb5231f7f05c08713
          path: libbacktrace
      - name: Build libbacktrace
        run: |
          apk add build-base git
          cd libbacktrace && ./configure && make && make install
      - name: make
        run: make SERVER_CFLAGS='-Werror' USE_LIBBACKTRACE=yes
      - name: testprep
        run: apk add tcl procps tclx
      - name: module api commandresult loop
        run: |
          CFLAGS='-Werror' ./runtest-moduleapi \
            --verbose \
            --dump-logs \
            --single unit/moduleapi/commandresult \
            --loops ${{ inputs.loops || github.event.inputs.loops }}

  reply-schemas-commandresult-loop:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: prep
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        run: |
          echo "GITHUB_REPOSITORY=${{ inputs.use_repo || github.event.inputs.use_repo }}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{ inputs.use_git_ref || github.event.inputs.use_git_ref }}" >> $GITHUB_ENV
          echo "loops=${{ inputs.loops || github.event.inputs.loops }}" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.use_repo || github.event.inputs.use_repo || github.repository }}
          ref: ${{ inputs.use_git_ref || github.event.inputs.use_git_ref || github.ref }}
      - name: Install libbacktrace
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ianlancetaylor/libbacktrace
          ref: b9e40069c0b47a722286b94eb5231f7f05c08713
          path: libbacktrace
      - name: Build libbacktrace
        run: cd libbacktrace && ./configure && make && sudo make install
      - name: make
        run: make SERVER_CFLAGS='-Werror -DLOG_REQ_RES' USE_LIBBACKTRACE=yes
      - name: testprep
        run: sudo apt-get install tcl8.6 tclx
      - name: module api commandresult loop
        run: |
          CFLAGS='-Werror' ./runtest-moduleapi \
            --log-req-res \
            --no-latency \
            --dont-clean \
            --force-resp3 \
            --dont-pre-clean \
            --verbose \
            --dump-logs \
            --single unit/moduleapi/commandresult \
            --loops ${{ inputs.loops || github.event.inputs.loops }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e # v4.1.0
        with:
          path: "./utils/req-res-validator/requirements.txt"
      - name: validator
        run: ./utils/req-res-log-validator.py --verbose --fail-missing-reply-schemas
